	subroutine initmeta (metaf,imeta,level, ifile, namlis, nfi, wflag,
     1    psfdir,calbname,calgridX,calgridY, version, STDscale,PSFuncscale)
	character*(*) metaf,level, ifile, namlis,
     1      psfdir,calbname, version
	integer imeta,L,L2,L3,L4,L5,numchar,ib, nfi
	integer calgridX,calgridY
	integer*2 wflag (nfi,4), temp (4)
	real*4 STDscale(4),PSFuncscale(4)
	

	do ib=1,4
	  temp(ib)  = 0
	  if ( any ( wflag ( 1:nfi,ib ) ==1 ) ) then
		temp(ib)  = 1
	  endif
	enddo

	L = numchar(namlis)
	L2 = numchar(ifile)
	L4 = numchar(psfdir)
	L5 = numchar(calbname)

	open (unit=imeta,file=metaf)

	write (imeta,'(a)') '\ WISE meta-data for WPHOT'
	write (imeta,'(a,a)') '\ Generated by WPHOT vsn ',version
	write (imeta,'(a)') '\ '
	write (imeta,'(a,a)') '\ namelist: ',namlis(1:L)
	write (imeta,'(a,a)') '\ Frame level: ',level(1:3)
	write (imeta,'(a,a)') '\ Input file: ',ifile(1:L2)
c	write (imeta,'(a,a)') '\ ApCorr Directory: ',apcorrdir(1:l3)
	write (imeta,'(a,a)') '\ PSF Directory: ',psfdir(1:l4)
c	write (imeta,'(a,a)') '\ apcorr/psf base name: ',calbname(1:l5)
	write (imeta,'(a,2i3)') '\ PSF FP grid size: ',calgridX,calgridY
	write (imeta,'(a,4i4)') '\ bands engaged: ',(temp(ib),ib=1,4)
	write (imeta,'(a,4F8.2)') '\ STD/UNC scaling: ',(STDscale(ib),ib=1,4)
	write (imeta,'(a,4F8.2)') '\ PSF/UNC scaling: ',(PSFuncscale(ib),ib=1,4)

	
	write (imeta,'(a)') '\ '
	write (imeta,'(a)') '|    name                |band| type| value            |     comment            
     1                                                   |'
	write (imeta,'(a)') '|    c                   |i   |   c | c                |     c                 
     1                                                    |'

	return
	end

