! wpro.inc:   Set some dimensioning parameters for wpro.f

	integer, parameter :: maxframes = 224	   ! maximum coverage x 4   ;   08Jan2018  THJ

	integer, parameter :: maxframesin = 112  ! maximum # input frames   ;   08Jan2018  THJ
						   ! in any one band

 	integer, parameter :: maxpix = 50000 	   ! maximum number of pixels
						   ! per band in the solution 
						   ! for any one source
